gui:
  skipDiscardChangeWarning: true
  skipStashWarning: true
  skipNoStagedFilesWarning: true
  nerdFontsVersion: "3"
git:
  overrideGpg: true
  paging:
    externalDiffCommand: difft --color=always --background=light --display inline
notARepository: skip
