"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

palette = 'tokyonight_storm'

[palettes.tokyonight_storm]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

bright-black = '#414868'
bright-red = '#f7768e'
bright-green = '#9ece6a'
bright-yellow = '#e0af68'
bright-blue = '#7aa2f7'
bright-magenta = '#bb9af7'
bright-cyan = '#7dcfff'
bright-white = '#c0caf5'

[aws]
disabled = true
