import = ["~/.config/alacritty/tokyonight_moon.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]


[window]
decorations = "None"
option_as_alt = "Both"
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
normal = { family = "MonaspiceNe NFM" }
size = 20

[env]
TERM = "alacritty-direct"
