import = ["~/.config/alacritty/theme.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new -s main"]

[window]
decorations = "None"
option_as_alt = "Both"
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
normal = { family = "MonaspiceNe NFM" }
size = 20

[env]
TERM = "alacritty-direct"
