[colors.primary]
background = '#222433'
foreground = '#c8d3f5'

[colors.cursor]
cursor = '#c8d3f5'
text = '#222433'

[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#575c71'

[colors.bright]
black = '#313445'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

[[colors.indexed_colors]]
index = 16
color = '#1b1d2b'

[[colors.indexed_colors]]
index = 17
color = '#2f3955'

[[colors.indexed_colors]]
index = 18
color = '#44557f'

[[colors.indexed_colors]]
index = 19
color = '#5871aa'

[[colors.indexed_colors]]
index = 20
color = '#6d8dd4'

[[colors.indexed_colors]]
index = 21
color = '#82aaff'

[[colors.indexed_colors]]
index = 22
color = '#3c453e'

[[colors.indexed_colors]]
index = 23
color = '#4a5b64'

[[colors.indexed_colors]]
index = 24
color = '#58728b'

[[colors.indexed_colors]]
index = 25
color = '#6688b1'

[[colors.indexed_colors]]
index = 26
color = '#749ed8'

[[colors.indexed_colors]]
index = 27
color = '#82b5fe'

[[colors.indexed_colors]]
index = 28
color = '#5e6e52'

[[colors.indexed_colors]]
index = 29
color = '#657e74'

[[colors.indexed_colors]]
index = 30
color = '#6d8e96'

[[colors.indexed_colors]]
index = 31
color = '#749fb9'

[[colors.indexed_colors]]
index = 32
color = '#7cafdb'

[[colors.indexed_colors]]
index = 33
color = '#83c0fd'

[[colors.indexed_colors]]
index = 34
color = '#7f9665'

[[colors.indexed_colors]]
index = 35
color = '#80a184'

[[colors.indexed_colors]]
index = 36
color = '#81aba2'

[[colors.indexed_colors]]
index = 37
color = '#82b6c0'

[[colors.indexed_colors]]
index = 38
color = '#83c0de'

[[colors.indexed_colors]]
index = 39
color = '#84cbfd'

[[colors.indexed_colors]]
index = 40
color = '#a1bf79'

[[colors.indexed_colors]]
index = 41
color = '#9bc393'

[[colors.indexed_colors]]
index = 42
color = '#96c8ad'

[[colors.indexed_colors]]
index = 43
color = '#90ccc8'

[[colors.indexed_colors]]
index = 44
color = '#8ad1e2'

[[colors.indexed_colors]]
index = 45
color = '#85d6fc'

[[colors.indexed_colors]]
index = 46
color = '#c3e88d'

[[colors.indexed_colors]]
index = 47
color = '#b6e6a3'

[[colors.indexed_colors]]
index = 48
color = '#aae5b9'

[[colors.indexed_colors]]
index = 49
color = '#9ee3cf'

[[colors.indexed_colors]]
index = 50
color = '#92e2e5'

[[colors.indexed_colors]]
index = 51
color = '#86e1fc'

[[colors.indexed_colors]]
index = 52
color = '#482e3b'

[[colors.indexed_colors]]
index = 53
color = '#564662'

[[colors.indexed_colors]]
index = 54
color = '#645e89'

[[colors.indexed_colors]]
index = 55
color = '#7276b0'

[[colors.indexed_colors]]
index = 56
color = '#808ed7'

[[colors.indexed_colors]]
index = 57
color = '#8ea6ff'

[[colors.indexed_colors]]
index = 58
color = '#63524b'

[[colors.indexed_colors]]
index = 59
color = '#6c656e'

[[colors.indexed_colors]]
index = 60
color = '#757892'

[[colors.indexed_colors]]
index = 61
color = '#7d8bb6'

[[colors.indexed_colors]]
index = 62
color = '#869eda'

[[colors.indexed_colors]]
index = 63
color = '#8fb1fe'

[[colors.indexed_colors]]
index = 64
color = '#7e765a'

[[colors.indexed_colors]]
index = 65
color = '#81847b'

[[colors.indexed_colors]]
index = 66
color = '#85929b'

[[colors.indexed_colors]]
index = 67
color = '#89a0bc'

[[colors.indexed_colors]]
index = 68
color = '#8caedc'

[[colors.indexed_colors]]
index = 69
color = '#90bcfd'

[[colors.indexed_colors]]
index = 70
color = '#999969'

[[colors.indexed_colors]]
index = 71
color = '#97a387'

[[colors.indexed_colors]]
index = 72
color = '#96aca4'

[[colors.indexed_colors]]
index = 73
color = '#94b5c1'

[[colors.indexed_colors]]
index = 74
color = '#92bedf'

[[colors.indexed_colors]]
index = 75
color = '#91c7fc'

[[colors.indexed_colors]]
index = 76
color = '#b4bd79'

[[colors.indexed_colors]]
index = 77
color = '#adc193'

[[colors.indexed_colors]]
index = 78
color = '#a6c6ad'

[[colors.indexed_colors]]
index = 79
color = '#9fcac7'

[[colors.indexed_colors]]
index = 80
color = '#99cee1'

[[colors.indexed_colors]]
index = 81
color = '#92d3fb'

[[colors.indexed_colors]]
index = 82
color = '#cfe188'

[[colors.indexed_colors]]
index = 83
color = '#c3e09f'

[[colors.indexed_colors]]
index = 84
color = '#b7e0b6'

[[colors.indexed_colors]]
index = 85
color = '#abdfcd'

[[colors.indexed_colors]]
index = 86
color = '#9fdee3'

[[colors.indexed_colors]]
index = 87
color = '#93defa'

[[colors.indexed_colors]]
index = 88
color = '#76404c'

[[colors.indexed_colors]]
index = 89
color = '#7d5470'

[[colors.indexed_colors]]
index = 90
color = '#846793'

[[colors.indexed_colors]]
index = 91
color = '#8c7bb7'

[[colors.indexed_colors]]
index = 92
color = '#938fdb'

[[colors.indexed_colors]]
index = 93
color = '#9aa3ff'

[[colors.indexed_colors]]
index = 94
color = '#8a5f57'

[[colors.indexed_colors]]
index = 95
color = '#8d6e78'

[[colors.indexed_colors]]
index = 96
color = '#917e9a'

[[colors.indexed_colors]]
index = 97
color = '#948ebb'

[[colors.indexed_colors]]
index = 98
color = '#989edc'

[[colors.indexed_colors]]
index = 99
color = '#9baefd'

[[colors.indexed_colors]]
index = 100
color = '#9e7e62'

[[colors.indexed_colors]]
index = 101
color = '#9e8981'

[[colors.indexed_colors]]
index = 102
color = '#9d95a0'

[[colors.indexed_colors]]
index = 103
color = '#9da1bf'

[[colors.indexed_colors]]
index = 104
color = '#9daddd'

[[colors.indexed_colors]]
index = 105
color = '#9db9fc'

[[colors.indexed_colors]]
index = 106
color = '#b29c6d'

[[colors.indexed_colors]]
index = 107
color = '#aea48a'

[[colors.indexed_colors]]
index = 108
color = '#aaaca6'

[[colors.indexed_colors]]
index = 109
color = '#a6b4c2'

[[colors.indexed_colors]]
index = 110
color = '#a2bcdf'

[[colors.indexed_colors]]
index = 111
color = '#9ec4fb'

[[colors.indexed_colors]]
index = 112
color = '#c6bb79'

[[colors.indexed_colors]]
index = 113
color = '#bebf92'

[[colors.indexed_colors]]
index = 114
color = '#b7c3ac'

[[colors.indexed_colors]]
index = 115
color = '#afc8c6'

[[colors.indexed_colors]]
index = 116
color = '#a7cce0'

[[colors.indexed_colors]]
index = 117
color = '#9fd0fa'

[[colors.indexed_colors]]
index = 118
color = '#dbda84'

[[colors.indexed_colors]]
index = 119
color = '#cfda9b'

[[colors.indexed_colors]]
index = 120
color = '#c3dbb3'

[[colors.indexed_colors]]
index = 121
color = '#b7dbca'

[[colors.indexed_colors]]
index = 122
color = '#acdbe1'

[[colors.indexed_colors]]
index = 123
color = '#a0dbf9'

[[colors.indexed_colors]]
index = 124
color = '#a3515d'

[[colors.indexed_colors]]
index = 125
color = '#a4617d'

[[colors.indexed_colors]]
index = 126
color = '#a5719e'

[[colors.indexed_colors]]
index = 127
color = '#a580be'

[[colors.indexed_colors]]
index = 128
color = '#a690de'

[[colors.indexed_colors]]
index = 129
color = '#a79fff'

[[colors.indexed_colors]]
index = 130
color = '#b16b64'

[[colors.indexed_colors]]
index = 131
color = '#af7882'

[[colors.indexed_colors]]
index = 132
color = '#ad85a1'

[[colors.indexed_colors]]
index = 133
color = '#ab91c0'

[[colors.indexed_colors]]
index = 134
color = '#aa9ede'

[[colors.indexed_colors]]
index = 135
color = '#a8abfd'

[[colors.indexed_colors]]
index = 136
color = '#be856b'

[[colors.indexed_colors]]
index = 137
color = '#ba8f88'

[[colors.indexed_colors]]
index = 138
color = '#b699a5'

[[colors.indexed_colors]]
index = 139
color = '#b2a3c2'

[[colors.indexed_colors]]
index = 140
color = '#adacdf'

[[colors.indexed_colors]]
index = 141
color = '#a9b6fc'

[[colors.indexed_colors]]
index = 142
color = '#cca072'

[[colors.indexed_colors]]
index = 143
color = '#c5a68d'

[[colors.indexed_colors]]
index = 144
color = '#beada8'

[[colors.indexed_colors]]
index = 145
color = '#b8b4c4'

[[colors.indexed_colors]]
index = 146
color = '#b1bbdf'

[[colors.indexed_colors]]
index = 147
color = '#abc1fa'

[[colors.indexed_colors]]
index = 148
color = '#d9ba78'

[[colors.indexed_colors]]
index = 149
color = '#d0bd92'

[[colors.indexed_colors]]
index = 150
color = '#c7c1ac'

[[colors.indexed_colors]]
index = 151
color = '#bec5c5'

[[colors.indexed_colors]]
index = 152
color = '#b5c9df'

[[colors.indexed_colors]]
index = 153
color = '#accdf9'

[[colors.indexed_colors]]
index = 154
color = '#e7d47f'

[[colors.indexed_colors]]
index = 155
color = '#dbd597'

[[colors.indexed_colors]]
index = 156
color = '#d0d5af'

[[colors.indexed_colors]]
index = 157
color = '#c4d6c7'

[[colors.indexed_colors]]
index = 158
color = '#b9d7df'

[[colors.indexed_colors]]
index = 159
color = '#add8f7'

[[colors.indexed_colors]]
index = 160
color = '#d1636e'

[[colors.indexed_colors]]
index = 161
color = '#cb6e8b'

[[colors.indexed_colors]]
index = 162
color = '#c57aa8'

[[colors.indexed_colors]]
index = 163
color = '#bf85c5'

[[colors.indexed_colors]]
index = 164
color = '#b991e2'

[[colors.indexed_colors]]
index = 165
color = '#b39cff'

[[colors.indexed_colors]]
index = 166
color = '#d87870'

[[colors.indexed_colors]]
index = 167
color = '#d1828c'

[[colors.indexed_colors]]
index = 168
color = '#ca8ba9'

[[colors.indexed_colors]]
index = 169
color = '#c394c5'

[[colors.indexed_colors]]
index = 170
color = '#bc9ee1'

[[colors.indexed_colors]]
index = 171
color = '#b5a7fd'

[[colors.indexed_colors]]
index = 172
color = '#de8d73'

[[colors.indexed_colors]]
index = 173
color = '#d6958e'

[[colors.indexed_colors]]
index = 174
color = '#ce9ca9'

[[colors.indexed_colors]]
index = 175
color = '#c6a4c5'

[[colors.indexed_colors]]
index = 176
color = '#beabe0'

[[colors.indexed_colors]]
index = 177
color = '#b6b3fb'

[[colors.indexed_colors]]
index = 178
color = '#e5a376'

[[colors.indexed_colors]]
index = 179
color = '#dca890'

[[colors.indexed_colors]]
index = 180
color = '#d3aeaa'

[[colors.indexed_colors]]
index = 181
color = '#cab3c5'

[[colors.indexed_colors]]
index = 182
color = '#c1b9df'

[[colors.indexed_colors]]
index = 183
color = '#b7bef9'

[[colors.indexed_colors]]
index = 184
color = '#ecb878'

[[colors.indexed_colors]]
index = 185
color = '#e2bb92'

[[colors.indexed_colors]]
index = 186
color = '#d7bfab'

[[colors.indexed_colors]]
index = 187
color = '#cdc3c5'

[[colors.indexed_colors]]
index = 188
color = '#c3c6de'

[[colors.indexed_colors]]
index = 189
color = '#b9caf8'

[[colors.indexed_colors]]
index = 190
color = '#f3cd7b'

[[colors.indexed_colors]]
index = 191
color = '#e7cf94'

[[colors.indexed_colors]]
index = 192
color = '#dcd0ac'

[[colors.indexed_colors]]
index = 193
color = '#d1d2c5'

[[colors.indexed_colors]]
index = 194
color = '#c6d4dd'

[[colors.indexed_colors]]
index = 195
color = '#bad5f6'

[[colors.indexed_colors]]
index = 196
color = '#ff757f'

[[colors.indexed_colors]]
index = 197
color = '#f27c98'

[[colors.indexed_colors]]
index = 198
color = '#e583b2'

[[colors.indexed_colors]]
index = 199
color = '#d98acb'

[[colors.indexed_colors]]
index = 200
color = '#cc91e5'

[[colors.indexed_colors]]
index = 201
color = '#c099ff'

[[colors.indexed_colors]]
index = 202
color = '#ff857d'

[[colors.indexed_colors]]
index = 203
color = '#f28b96'

[[colors.indexed_colors]]
index = 204
color = '#e691b0'

[[colors.indexed_colors]]
index = 205
color = '#da98c9'

[[colors.indexed_colors]]
index = 206
color = '#cd9ee3'

[[colors.indexed_colors]]
index = 207
color = '#c1a4fd'

[[colors.indexed_colors]]
index = 208
color = '#ff957b'

[[colors.indexed_colors]]
index = 209
color = '#f39b95'

[[colors.indexed_colors]]
index = 210
color = '#e7a0ae'

[[colors.indexed_colors]]
index = 211
color = '#dba5c8'

[[colors.indexed_colors]]
index = 212
color = '#cfaae1'

[[colors.indexed_colors]]
index = 213
color = '#c3b0fb'

[[colors.indexed_colors]]
index = 214
color = '#fea67a'

[[colors.indexed_colors]]
index = 215
color = '#f3aa93'

[[colors.indexed_colors]]
index = 216
color = '#e7aeac'

[[colors.indexed_colors]]
index = 217
color = '#dcb3c6'

[[colors.indexed_colors]]
index = 218
color = '#d0b7df'

[[colors.indexed_colors]]
index = 219
color = '#c4bbf9'

[[colors.indexed_colors]]
index = 220
color = '#ffb678'

[[colors.indexed_colors]]
index = 221
color = '#f3b991'

[[colors.indexed_colors]]
index = 222
color = '#e8bdab'

[[colors.indexed_colors]]
index = 223
color = '#ddc0c4'

[[colors.indexed_colors]]
index = 224
color = '#d1c4dd'

[[colors.indexed_colors]]
index = 225
color = '#c6c7f7'

[[colors.indexed_colors]]
index = 226
color = '#ffc777'

[[colors.indexed_colors]]
index = 227
color = '#f4c990'

[[colors.indexed_colors]]
index = 228
color = '#e9cba9'

[[colors.indexed_colors]]
index = 229
color = '#ddcec2'

[[colors.indexed_colors]]
index = 230
color = '#d3d0db'

[[colors.indexed_colors]]
index = 231
color = '#c8d3f5'

[[colors.indexed_colors]]
index = 232
color = '#1b1d2b'

[[colors.indexed_colors]]
index = 233
color = '#222433'

[[colors.indexed_colors]]
index = 234
color = '#2a2c3c'

[[colors.indexed_colors]]
index = 235
color = '#313445'

[[colors.indexed_colors]]
index = 236
color = '#393c4e'

[[colors.indexed_colors]]
index = 237
color = '#404456'

[[colors.indexed_colors]]
index = 238
color = '#484c5f'

[[colors.indexed_colors]]
index = 239
color = '#4f5468'

[[colors.indexed_colors]]
index = 240
color = '#575c71'

[[colors.indexed_colors]]
index = 241
color = '#5e647a'

[[colors.indexed_colors]]
index = 242
color = '#666c82'

[[colors.indexed_colors]]
index = 243
color = '#6d748b'

[[colors.indexed_colors]]
index = 244
color = '#757b94'

[[colors.indexed_colors]]
index = 245
color = '#7c839d'

[[colors.indexed_colors]]
index = 246
color = '#848ba5'

[[colors.indexed_colors]]
index = 247
color = '#8b93ae'

[[colors.indexed_colors]]
index = 248
color = '#939bb7'

[[colors.indexed_colors]]
index = 249
color = '#9aa3c0'

[[colors.indexed_colors]]
index = 250
color = '#a2abc9'

[[colors.indexed_colors]]
index = 251
color = '#a9b3d1'

[[colors.indexed_colors]]
index = 252
color = '#b1bbda'

[[colors.indexed_colors]]
index = 253
color = '#b8c3e3'

[[colors.indexed_colors]]
index = 254
color = '#c0cbec'

[[colors.indexed_colors]]
index = 255
color = '#c8d3f5'
